---
title: "Data Cleaning"
output: github_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(readxl)
library(stringr)
library(rvest)
library(httr)
library(forstringr)
```


## Data Cleaning

### Weather Condition

```{r}
noaa = read_csv("data/weather.csv", na = c("","NA"))

noaa_df = noaa %>%
  janitor::clean_names() %>% 
  select(date, starts_with("hourly")) %>% 
  mutate(
    date = str_replace_all(date, "T", "-")
  ) %>% 
  separate(date, c("year", "month", "day", "hour", "minute", "second"), remove = FALSE) %>% 
  filter(minute == "51") %>% 
  select(-minute, -second) %>% 
  mutate(
    date = as.Date(str_left(date, n = 10), format = "%Y-%m-%d"),
    year = as.numeric(year),
    month = as.numeric(month),
    day = as.numeric(day),
    hour = as.numeric(hour)
  )

daily_weather = noaa %>%
  janitor::clean_names() %>% 
  select(date, daily_weather) %>% 
  filter(!is.na(daily_weather)) %>% 
  mutate(
    date = str_replace_all(date, "T", "-")
  ) %>% 
  separate(date, c("year", "month", "day", "hour", "minute", "second")) %>% 
  select(-c(hour:second)) %>% 
  mutate(
    year = as.numeric(year),
    month = as.numeric(month),
    day = as.numeric(day)
  )

noaa_df = left_join(noaa_df, daily_weather, by = c("year", "month", "day"))
```

### COVID

```{r}
covid = 
  GET("https://data.cityofnewyork.us/resource/rc75-m7u3.csv") %>% 
  content("parsed") 

covid_df = covid %>% 
  select(date = date_of_interest, case_count) %>%
  filter(date < "2022-01-31" & date >= "2021-10-31") %>% 
  separate(date, c("year", "month", "day"), remove = FALSE) %>% 
  mutate(
    date = as.Date(date, format = "%Y-%m-%d")
  ) %>% 
  mutate_if(is.character, as.numeric)
```

### Delay

```{r}
read_csv_function = function(path) {
  
  df = read_csv(path, 
                skip = 7, 
                cols(.default = "c")) %>%
    janitor::row_to_names(1) %>% 
    janitor::clean_names()
  
  df
  
}

delay_cancel = 
  tibble(
    files = list.files("data/delay/"),
    path = str_c("data/delay/", files)
  ) %>% 
  mutate(data = map(path, read_csv_function)) %>% 
  unnest(data) %>% 
  select(-files, -path) %>%
  mutate(
    airline_name = case_when(
      carrier_code == "9E" ~ "Endeavor Air",
      carrier_code == "AA" ~ "American Airlines",
      carrier_code == "AS" ~ "Alaska Airlines",
      carrier_code == "B6" ~ "JetBlue Airways",
      carrier_code == "DL" ~ "Delta Air Lines",
      carrier_code == "UA" ~ "United Air Lines",
      carrier_code == "YX" ~ "Republic Airways",
      TRUE      ~ ""
    ),
    scheduled_hour = str_left(scheduled_departure_time, 2)
  ) %>% 
  separate(date_mm_dd_yyyy, into = c("month", "day", "year"), sep = "/", remove = FALSE) %>%
  mutate(
    year = as.numeric(year),
    month = as.numeric(month),
    day = as.numeric(day),
    date_mm_dd_yyyy = as.Date(date_mm_dd_yyyy, format = "%m/%d/%Y")
  ) %>%
  select(airline_name, date = date_mm_dd_yyyy, everything(), -carrier_code, -tail_number, -wheels_off_time) %>% 
  arrange(date) %>% 
  relocate(scheduled_hour, .before = scheduled_departure_time)

full_delay_df = 
  delay_cancel %>% 
  filter(actual_elapsed_time_minutes != 0) %>% 
  mutate(
    delay_minutes = as.numeric(as.POSIXct(actual_departure_time, format = "%H:%M") - as.POSIXct(scheduled_departure_time, format = "%H:%M")) / 60,
    delay_minutes = ifelse(delay_minutes < -100, delay_minutes + 1440, delay_minutes)
  ) %>% 
  select(-departure_delay_minutes) %>% 
  relocate(delay_minutes, .after = actual_departure_time)
```

### Cancelation

```{r}
full_cancel_df = 
  delay_cancel %>% 
  filter(actual_elapsed_time_minutes == 0) %>% 
  select(airline_name:scheduled_departure_time, scheduled_elapsed_time_minutes)
```

### Airport Info

```{r}
airport = read_csv("data/us-airports.csv") %>% 
  slice(-1) %>% 
  select(airport = iata_code, name, lat = latitude_deg, long = longitude_deg, region_name, local_region, municipality)

airport_info =
  delay_cancel %>% 
  distinct(destination_airport) %>% 
  rename(airport = destination_airport) %>% 
  rbind("JFK") %>% 
  arrange(airport)

airport_info = left_join(airport_info, airport, by = "airport")
```


## Export

```{r}
write_csv(noaa_df, "tidied_data/weather.csv")
write_csv(covid_df, "tidied_data/covid.csv")
write_csv(full_delay_df, "tidied_data/delay.csv")
write_csv(full_cancel_df, "tidied_data/cancel.csv")
write_csv(airport_info, "tidied_data/airport.csv")
```

