---
title: "Delay Interaction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(plotly)

raw_df = read_csv("Reg_data_exp/raw_df.csv")
```

categorical variables: airline, month, hour



## Interaction between categorical variables {.tabset}
```{r, include = FALSE}
hour_air = function(air){
  raw_df %>% 
  filter(
    airline == air) %>%     
  mutate(
    mean = mean(delay),
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = "rgb(255, 65, 54)",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))
}

hour_air_0 = function(air){
raw_df %>% 
  filter(
    delay == 0:120,
    airline == air) %>%     
  mutate(
    mean = mean(delay),
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = "rgb(255, 65, 54)",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))
}

hour_air_120 = function(air){
raw_df %>% 
  filter(
    delay > 120,
    airline == "JetBlue Airways") %>%     
  mutate(
    mean = mean(delay),
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = "rgb(255, 65, 54)",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))
}

```

### hour*airline 

#### Before stratification
```{r, echo = FALSE}
raw_df %>% 
  mutate(
    mean = mean(delay),
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = "rgb(255, 65, 54)",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))

raw_df %>% 
  filter(
    delay == 0:120) %>%     
  mutate(
    mean = mean(delay),
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = "rgb(255, 65, 54)",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))

raw_df %>% 
  filter(
    delay > 120) %>%     
  mutate(
    mean = mean(delay),
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = "rgb(255, 65, 54)",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))

```

#### Stratification by airline {.tabset}
##### Alaska
```{r, echo = FALSE}
hour_air("Alaska Airlines")
```

##### American
```{r, echo = FALSE}
hour_air("American Airlines")
```

##### Delta
```{r, echo = FALSE}
hour_air("Delta Air Lines")
```

##### Endeavor
```{r, echo = FALSE}
hour_air("Endeavor Air")
```

##### JetBlue
```{r, echo = FALSE}
hour_air("JetBlue Airways")
```

##### Republic
```{r, echo = FALSE}
hour_air("Republic Airways")
```

##### United
```{r, echo = FALSE}
hour_air("United Air Lines")
```


### month*airline
```{r}
raw_df %>% 
  filter(
    airline == "JetBlue Airways") %>%     
  mutate(
    month = fct_reorder(month, delay)
    ) %>% 
  plot_ly(x = ~month, y = ~delay, color = ~month,
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Month"),
      yaxis = list(title = "Delay Time (Minutes)"))


raw_df %>% 
  filter(
    delay == 0:120,
    airline == "JetBlue Airways") %>%     
  mutate(
    month = fct_reorder(month, delay)
    ) %>% 
  plot_ly(x = ~month, y = ~delay, color = ~month,
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Month"),
      yaxis = list(title = "Delay Time (Minutes)"))


raw_df %>% 
  filter(
    delay > 120,
    airline == "JetBlue Airways") %>%     
  mutate(
    month = fct_reorder(month, delay)
    ) %>% 
  plot_ly(x = ~month, y = ~delay, color = ~month,
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Month"),
      yaxis = list(title = "Delay Time (Minutes)"))

```

### month*hour
```{r}
raw_df %>% 
  filter(
    month == "Nov") %>%     
  mutate(
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = ~hour_c,
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))


raw_df %>% 
  filter(
    delay == 0:120,
    month == "Nov") %>%     
  mutate(
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = ~hour_c,
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))


raw_df %>% 
  filter(
    delay > 120,
    month == "Nov") %>%     
  mutate(
    hour_c = fct_reorder(hour_c, delay)
    ) %>% 
  plot_ly(x = ~hour_c, y = ~delay, color = ~hour_c,
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Hour"),
      yaxis = list(title = "Delay Time (Minutes)"))

```



##### carrier*airline
```{r}
raw_df %>% 
  filter(
    delay > 0,
    airline == "JetBlue Airways") %>%
  plot_ly(x = ~carrierd, y = ~delay, 
          type = 'scatter', mode = 'markers', alpha = .5) %>% 
  layout(
    xaxis = list(title = "Carrier Delay Time (Minutes)"),
    yaxis = list(title = "Delay Time (Minutes)"))
```

##### carrier*month
```{r}
raw_df %>% 
  filter(
    delay > 0,
    month == "Nov") %>%
  plot_ly(x = ~carrierd, y = ~delay, 
          type = 'scatter', mode = 'markers', alpha = .5) %>% 
  layout(
    xaxis = list(title = "Carrier Delay Time (Minutes)"),
    yaxis = list(title = "Delay Time (Minutes)"))
```

##### carrier*hour
```{r}
raw_df %>% 
  filter(
    delay > 0,
    hour_c == "noon") %>%
  plot_ly(x = ~carrierd, y = ~delay, 
          type = 'scatter', mode = 'markers', alpha = .5) %>% 
  layout(
    xaxis = list(title = "Carrier Delay Time (Minutes)"),
    yaxis = list(title = "Delay Time (Minutes)"))
```





