---
title: "Delay Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)

delay = read_csv("tidied_data/delay.csv")

delay = 
  delay %>% 
  filter(delay_minutes > 0) %>% 
  group_by(month, day, airline_name) %>% 
  mutate(
    count = n(),
    mean = mean(delay_minutes)
  ) %>% 
  ungroup() %>% 
  mutate(
    month = recode(month, "11" = "Nov, 2021", "12" = "Dec, 2021", "1" = "Jan, 2022")
  ) 
```


```{r, echo = FALSE}
airlines = delay %>% distinct(airline_name) %>% pull()

selectInput(
  inputId = "airline_choice",
  label = h3("Airline"),
  choices = airlines,
  selected = "JetBlue Airways"
)

months = 
  delay %>% 
  distinct(month) %>% 
  pull()

radioButtons(
  inputId = "month_choice",
  label = h3("Month"),
  choices = months,
  selected = "Nov, 2021"
)
```



### Number of Delays on Each Day 

```{r, echo = FALSE}
renderPlotly({
  delay %>%
    filter(
      airline_name == input[["airline_choice"]],
      month == input[["month_choice"]]
    ) %>% 
mutate(
  text_label = str_c("Date: ", date, "\nCount: ", count)
) %>% 
  plot_ly(x = ~day, text = ~text_label, hoverinfo = "text",
          type = "histogram", mode = "markers", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Day"),
    yaxis = list(title = "Count"))

})
```



### Distribution of Delay Time on Each Day

```{r, echo = FALSE}
renderPlotly({

  delay %>% 

    filter(
      airline_name == input[["airline_choice"]],
      month == input[["month_choice"]]
    ) %>% 
    mutate(

      text_label = str_c("Date: ", date)
    ) %>% 
    plot_ly(x = ~day, y = ~delay_minutes, text = ~text_label, hoverinfo = "text",
          type = 'box', mode = 'markers', alpha = .5) %>% 
    layout(
      xaxis = list(title = "Day"),
      yaxis = list(title = "Delay Time (Minutes)"))
})
```

```{r, eval = FALSE, echo = FALSE}
mutate(
  text_label = str_c("Date: ", date, "\nCount: ", count)
) %>% 
  plot_ly(x = ~day, y = ~count, text = ~text_label, hoverinfo = "text",
          type = "bar", mode = "markers", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Day"),
    yaxis = list(title = "Count"))


mutate(
>>>>>>> d69bf693a373ebe551a923063941bd0e1fbb93e4
  text_label = str_c("Date: ", date)
) %>% 
plot_ly(x = ~day, y = ~delay_minutes, text = ~text_label, hoverinfo = "text",
        type = 'box', mode = 'markers', alpha = .5) %>% 
  layout(
    xaxis = list(title = "Day"),
    yaxis = list(title = "Delay Time (Minutes)"))
})
```


