---
title: "Destination Airport"
output: html_document

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(plotly)

delay = read_csv("tidied_data/delay.csv")
cancel = read_csv("tidied_data/cancel.csv")

```

<br>

## Airlines {.tabset}
### Alaska Airlines
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "Alaska Airlines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "Alaska Airlines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```

### American Airlines 
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "American Airlines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "American Airlines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```

### Delta Air Lines 
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "Delta Air Lines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "Delta Air Lines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```

### Endeavor Air  
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "Endeavor Air"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "Endeavor Air"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```
   
### JetBlue Airways
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "JetBlue Airways"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "JetBlue Airways"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```

### Republic Airways
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "Republic Airways"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "Republic Airways"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```

### United Air Lines
```{r, echo = FALSE}
  delay %>%
    filter(
      airline_name == "United Air Lines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text", 
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Delay ")

  cancel %>%
    filter(
      airline_name == "United Air Lines"
    ) %>% 
    group_by(destination_airport) %>% 
    mutate(
      count = n()
      ) %>% 
  ungroup() %>% 
  mutate(
    destination_airport = fct_reorder(destination_airport, count),
    text_label = str_c("Airpline: ", airline_name, "\nCount: ", count)
      ) %>% 
  plot_ly(x = ~destination_airport, text = ~text_label, hoverinfo = "text",
          color = "rgb(255, 65, 54)", type = "histogram", alpha = .5) %>% 
  layout(
    xaxis = list(title = "Destination Airport"),
    yaxis = list(title = "Count"),
    title = "Distribution of Cancelation")

```



