---
title: "Plot Delay Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

cancel = read_csv("tidied_data/cancel.csv")
covid = read_csv("tidied_data/covid.csv")
delay = read_csv("tidied_data/delay.csv")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
airlines = delay %>% distinct(airline_name) %>% pull()

selectInput(
  input = "airline_choice",
  label = h3("Airline"),
  choices = airlines,
  selected = "JetBlue Airways"
)

months = delay %>% 
  distinct(month) %>% 
  mutate(
    month = recode(month, "11" = "Nov, 2021", "12" = "Dec, 2021", "1" = "Jan, 2022")
  ) %>% 
  pull()

radioButtons(
  inputId = "month_choice",
  label = h3("Month"),
  choices = months,
  selected = "Nov, 2021"
)

```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
  
  delay %>% 
    filter(
      airline_name == input[["airline_choice"]],
      month == input[["month_choice"]]) %>% 
  group_by(month, day, airline_name) %>% 
  summarize(
    count = n()) %>% 
  plot_ly(x = ~day, y = ~count,
              type = 'bar', alpha = .5)

})
```


Column {data-width=600}
-----------------------------------------------------------------------

### Chart B

```{r}

delay %>% 
  filter(
      delay_minutes > 0,
      airline_name == input[["airline_choice"]],
      month == input[["month_choice"]]) %>% 
  group_by(day) %>% 
  mutate(
    count = n(),
    mean = mean(delay_minutes)) %>% 
  plot_ly(x = ~day, y = ~mean, 
          type = 'scatter', mode = 'markers') 
          #color = ~count, colors = 'Reds',marker = list(size = ~count, opacity = 0.5))

```


