---
title: "Visualization and EDA"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(ggplot2)
library(gganimate)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))


cancel = read_csv("tidied_data/cancel.csv")
covid = read_csv("tidied_data/covid.csv")
delay = read_csv("tidied_data/delay.csv")
weather = read_csv("tidied_data/weather.csv")

```


```{r}
delay %>% 
  group_by(date) %>% 
  summarize(
    count = n()
  ) %>% 
  ggplot(aes(x = date, y = count)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE)

delay %>% 
  group_by(month) %>% 
  summarize(
    count = n()
  ) %>% 
  ggplot(aes(x = count, y = as.factor(month), fill = month)) +
  geom_density_ridges(alpha = .5)


delay %>% 
  group_by(date, airline_name) %>% 
  summarize(
    count = n()
  ) %>% 
  ggplot(aes(x = date, y = count, color = airline_name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE)

delay %>% 
  group_by(month) %>% 
  filter(delay_minutes > 0) %>% 
  ggplot(aes(x = as.factor(month), y = delay_minutes)) +
  geom_violin()

cancel %>% 
  group_by(date) %>% 
  summarize(
    count = n()
  ) %>% 
  ggplot(aes(x = date, y = count)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE)


```

```{r, eval=FALSE}

# Make a ggplot, but add frame=year: one image per year

delay %>% 
  group_by(month) %>% 
  mutate(
    count = n()
  ) %>% 
  ungroup(month) %>% 
ggplot(aes(x = date, y = delay_minutes, size = count, color = airline_name)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  #scale_colour_manual(values = airline_name) +
  scale_size(range = c(1, 10)) 
  # Here comes the gganimate specific bits
  labs(title = 'Month: {frame_time}', x = 'date', y = 'delay_minutes') +
  transition_time(month) +
  ease_aes('linear')

# Save at gif:
anim_save("271-ggplot2-animated-gif-chart-with-gganimate2.gif")
```



```{r}
cancel_line = cancel %>% 
  group_by(date, airline_name) %>% 
  summarize(
    count = n()
  ) %>% 
  ggplot(aes(x = date, y = count, color = airline_name)) +
  geom_line()


covid_line = covid %>% 
  ggplot(aes(x = date, y = case_count)) +
  geom_line()

cancel_line + covid_line

```



